config/routes.rb
NewChupandero::Application.routes.draw do

  root :to => 'static_pages#index'

  match "chupanderos", to: 'static_pages#chupanderos'
  match "registro", to: 'static_pages#registro'
  match "contacto", to: 'static_pages#contacto'
  resources :bars

  get "static_pages/contacto"

  devise_for :users

  get '/map', to: 'bars#map'

  get '/join', to: 'static_pages#join'

end

app/models/bar.rb
class Bar < ActiveRecord::Base
  attr_accessible :description, :geo_address, :horary, :image1, :image2, :image3, :image4, :latitude, :logo,
  				   :longitude, :name, :page, :phone, :promo, :address, :email

  geocoded_by :geo_address
  after_validation :geocode

end

app/models/join.rb
class Join < ActiveRecord::Base
  attr_accessible :email
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  # GET /bars
  # GET /bars.json
  layout "registro", :only =>[:index, :new, :edit]
  before_filter :authenticate_user!, except: [:show, :map]

  def index
    @bars = Bar.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bars }
    end
  end

  # GET /bars/1
  # GET /bars/1.json
  def show
    @bar = Bar.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bar }
    end
  end

  # GET /bars/new
  # GET /bars/new.json
  def new
    @bar = Bar.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bar }
    end
  end

  # GET /bars/1/edit
  def edit
    @bar = Bar.find(params[:id])
  end

  # POST /bars
  # POST /bars.json
  def create
    @bar = Bar.new(params[:bar])

    respond_to do |format|
      if @bar.save
        format.html { redirect_to @bar, notice: 'Bar was successfully created.' }
        format.json { render json: @bar, status: :created, location: @bar }
      else
        format.html { render action: "new" }
        format.json { render json: @bar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bars/1
  # PUT /bars/1.json
  def update
    @bar = Bar.find(params[:id])

    respond_to do |format|
      if @bar.update_attributes(params[:bar])
        format.html { redirect_to @bar, notice: 'Bar was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bars/1
  # DELETE /bars/1.json
  def destroy
    @bar = Bar.find(params[:id])
    @bar.destroy

    respond_to do |format|
      format.html { redirect_to bars_url }
      format.json { head :no_content }
    end
  end

  def map
     @bar = Bar.find(params[:bar_id])
  end
end

app/controllers/joins_controller.rb
class JoinsController < ApplicationController
  
  def join
  	@join = Join.new
  end

  def create
    @join = Join.new(params[:join])

    respond_to do |format|
      if @join.save
        format.html { redirect_to @join, notice: 'Gracias por escribirnos, muy pronto nos pondremos en contacto contigo.' }
        format.json { render json: @join, status: :created, location: @join }
      else
        format.html { render action: "new" }
        format.json { render json: @join.errors, status: :unprocessable_entity }
      end
    end
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout "registro", :only =>[:chupanderos]

  def index
  	@bars = Bar.all
    @bar = Bar.last
  end
  def chupanderos
  end

  def contacto
  end

  def registro
  end 

  def join
    @join = Join.new
    respond_to do |format|
      format.html # new.html.erb
      format.json
      format.js
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bars_helper.rb
module BarsHelper
end

app/helpers/joins_helper.rb
module JoinsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/bars/_form.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <div class="span8 offset2">
        <%= form_for(@bar) do |f| %>
          <% if @bar.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@bar.errors.count, "error") %> prohibited this bar from being saved:</h2>
              <ul>
              <% @bar.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="field">
            <%= f.label :Nombre_del_bar %>
            <%= f.text_field :name %>
          </div>
          <div class="field">
            <%= f.label :Imagen_del_logo %>
            <%= f.text_field :logo %>
          </div>
          <div class="field">
            <%= f.label :Reseña %>
            <%= f.text_area :description, class: "span6", rows: 6 %>
          </div>
          <div class="field">
            <%= f.label :Direccion %>
            <%= f.text_area :address, class: "span6", rows:2 %>
          </div>
          <div class="field">
            <%= f.label :Email_del_bar %>
            <%= f.text_field :email %>
          </div>
          <div class="field">
            <%= f.label :Website %>
            <%= f.text_field :page   %>
          </div>
          <div class="field">
            <%= f.label :Telefono %>
            <%= f.text_area :phone, class: "span4", rows:2 %>
          </div>
          <div class="field">
            <%= f.label :Horarios %>
            <%= f.text_area :horary, class: "span6", rows:2 %>
          </div>
          <div class="field">
            <%= f.label :Promo %>
            <%= f.text_area :promo, class: "span6", rows:3 %>
          </div>
          <div class="field">
            <%= f.label :image1 %>
            <%= f.text_field :image1 %>
          </div>
          <div class="field">
            <%= f.label :image2 %>
            <%= f.text_field :image2 %>
          </div>
           <div class="field">
            <%= f.label :image3 %>
            <%= f.text_field :image3 %>
          </div>
           <div class="field">
            <%= f.label :image4 %>
            <%= f.text_field :image4 %>
          </div>
         <div class="field">
            <%= f.label :Direccion_en_Google %>
            <%= f.text_area :geo_address, class: "span4", rows: 2 %>
          </div>
          <div class="field">
            <%= f.label :Latitude %>
            <%= f.text_area :latitude, class: "span4", rows: 2  %>
          </div>
          <div class="field">
            <%= f.label :Longitude %>
            <%= f.text_area :longitude, class: "span4", rows: 2  %>
          </div>
          <div class="actions">
            <%= f.submit %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bars/_map.html.erb
<div class="modal-chupandero">
  <div style="float:right">
  	<button type="button" class="close-button" data-dismiss="modal" aria-hidden="true">X</button>
  </div>
  <div class="modal_body">
	<div class="span8">
		<iframe width="825" height="550" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com.mx/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=Puebla&amp;aq=&amp;sll=<%= @bar.latitude %>,<%= @bar.longitude %>&amp;sspn=<%= @bar.latitude %>,<%= @bar.longitude %>&amp;ie=UTF8&amp;hq=&amp;hnear=<%= @bar.geo_address%>&amp;ll=<%= @bar.latitude%>,<%= @bar.longitude %>&amp;spn=0.022397,0.038581&amp;t=m&amp;z=18&amp;output=embed&iwloc=near"></iframe>
	</div>
  </div>
</div>

app/views/bars/edit.html.erb
<h1>Editing bar</h1>

<%= render 'form' %>

<%= link_to 'Show', @bar %> |
<%= link_to 'Back', bars_path %>

app/views/bars/index.html.erb
<div class="container">
    <h1>Listing bars</h1>

    <table>
      <tr>
        <th>Name</th>
        <th>Logo</th>
        <th>Description</th>
        <th>Phone</th>
        <th>Horary</th>
        <th>Promo</th>
        <th>Image1</th>
        <th>Image2</th>
        <th>Page</th>
        <th>Geo address</th>
        <th>Latitude</th>
        <th>Longitude</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

    <% @bars.each do |bar| %>
      <tr>
        <td><%= bar.name %></td>
        <td><%= bar.logo %></td>
        <td><%= bar.description %></td>
        <td><%= bar.phone %></td>
        <td><%= bar.horary %></td>
        <td><%= bar.promo %></td>
        <td><%= bar.image1 %></td>
        <td><%= bar.image2 %></td>
        <td><%= bar.page %></td>
        <td><%= bar.geo_address %></td>
        <td><%= bar.latitude %></td>
        <td><%= bar.longitude %></td>
        <td><%= link_to 'Show', bar %></td>
        <td><%= link_to 'Edit', edit_bar_path(bar) %></td>
        <td><%= link_to 'Destroy', bar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </table>

    <br />

    <%= link_to 'New Bar', new_bar_path %>
</div>

app/views/bars/map.js.erb
var y = window.pageYOffset;
document.documentElement.style.overflowY = "hidden";

window.onscroll = function(){
	window.scroll(0, y);
};
$('#modal-id').fadeIn('fast');
$('#modal-id').html("<%= escape_javascript(render :partial => 'map', :object => @bar) %>");
$('#modal-id').click(function(){
	window.onscroll = null;
	document.documentElement.style.overflowY = "scroll";
});
$(document).keyup(function(e) {
  if (e.keyCode == 27) { $('#modal-id').show();
	window.onscroll = null;
	$('#modal-id').fadeOut('fast');
	document.documentElement.style.overflowY = "scroll";
   }   // esc
});

$('.close-button').click(function(){
	$('#modal-id').fadeOut('fast');
});

app/views/bars/new.html.erb
<div class="container">
	<h1>New bar</h1>

	<%= render 'form' %>

	<%= link_to 'Back', bars_path %>
</div>

app/views/bars/show.html.erb
<% content_for :meta do %>
  <% meta :keywords => %w(chupandero cerveza puebla amigos) %>
  <% meta [:property => "og:image", :content => @bar.logo] %>
  <% meta [:property => "og:description", :content => @bar.name] %>
  <% meta [:property => "og:type", :content => "website"] %>
  <% meta [:property => "og:title", :content => "Bar - #{@bar.name}"] %>
  <% meta [:property => "og:url", :content => "http://chupandero.com/bars/#{@bar.id}"] %>
<% end %>

  <div class="row-fluid">
    <div class="span12">
        <div class="span3" id="main_menu">
        <div class="main_logo">
          <%= link_to(image_tag(@bar.logo, style:"width:327px; height: 300px"), @bar.page, target: "_blank") %>
          <!-- <%= image_tag "http://maps.google.com/maps/api/staticmap?size=400x400&sensor=false&zoom=16&markers=#{@bar.latitude}%2C#{@bar.longitude}"%> -->
        <!--  <iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com.mx/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=Puebla&amp;aq=&amp;sll=23.554132,-102.6205&amp;sspn=19.738439,34.40918&amp;ie=UTF8&amp;hq=&amp;hnear=Circuito+Juan+Pablo+II,+Puebla&amp;ll=<%= @bar.latitude%>,<%= @bar.longitude %>&amp;spn=0.022397,0.038581&amp;t=m&amp;z=14&amp;output=embed&iwloc=near"></iframe>-->
        </div>
        <hr style="margin:0">
        <div style="text-align:center" id="bar_title">
          <%= @bar.name %>
        </div>
        <hr style="margin:0">
        <p id="bar_info">
          <img style="width:20px" src="http://i1275.photobucket.com/albums/y450/wuichotron/iconolugar_zps3f4a62c6.png"/>
          <%= @bar.address%>
          <br/>
          <%= link_to "Ver mapa", map_path(:bar_id => @bar.id), {:id => "modal", :rel => "tab", :remote => true, 'data-controls-modal' =>  "modal-window", 'data-backdrop' => true, 'data-keyboard' => true} %>
        </p>
        <p id="bar_info">
          <img style="width:20px" src="http://i1275.photobucket.com/albums/y450/wuichotron/iconocadena_zps32b20549.png"/>
          <%= link_to @bar.page, @bar.page, target: "_blank" %>
          <br/>
        </p>
        <% if @bar.email.present? %>
          <p id="bar_info">
            <img style="width:20px" src="http://i1275.photobucket.com/albums/y450/wuichotron/iconomensaje_zps27da851b.png"/>
            <%= link_to @bar.email, "#" %>
            <br/>
          </p>
        <% end %>
        <p id="bar_info">
          <img style="width:20px" src="http://i1275.photobucket.com/albums/y450/wuichotron/iconotiempo_zps4edce200.png"/>
          <%= @bar.horary %>
        </p>
        <p id="bar_info">
          <img style="width:20px" src="http://i1275.photobucket.com/albums/y450/wuichotron/iconoinfo_zps2b2a56c7.png"/>
          Teléfono: <%= @bar.phone %>
        </p>
      </div>
      <div class="row-fluid">
        <div style="margin-left: -44px; margin-top: -8px;">
          <div style="background-color:#f2f2f2" class="span9 offset3">
            <p id="notice"><%= notice %></p>
            <div id="myCarousel" style="height:378px; margin:0; box-shadow: 0px 6px 15px 2px; -webkit-box-shadow: 7px 6px 15px 1px;" class  ="carousel slide">
                  <!-- Carousel items -->
               <div class="carousel-inner">
              <div class="active item"><%= image_tag(@bar.image1, style: "max-height:378px; max-width: 900px ")%></div>
                <div class="item"><%= image_tag(@bar.image2,  style: "max-height:378px; max-width: 900px")%></div>
                <div class="item"><%= image_tag(@bar.image3,  style: "max-height:378px; max-width: 900px")%></div>
                <div class="item"><%= image_tag(@bar.image4,  style: "max-height:378px; max-width: 900px")%></div>
              </div>
              <!-- Carousel nav -->
              <a style="display:none" class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
              <a style="display:none" class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
            </div>
            <div class="span10">
              <h1 class="promo" >
                "<%= @bar.promo%>"
              </h1>
              <div style="float:right" class="fb-like" data-href="http://chupandero.com/bars/<%= @bar.id%>" data-send="false" data-layout="box_count" data-width="200" data-show-faces="false" data-action="recommend"></div>
              <div class="span9 offset1">
                <p class="resena">
                  <%= @bar.description.html_safe %>
                </p>
                <hr>
                <br>
                <div class="fb-comments" data-href="http://chupandero.com/bars/<%= @bar.id %>" data-width="650" data-num-posts="10"></div>
              </div>
            </div>
            <%= render 'layouts/footer' %>
          </div>
        </div>
      </div>
    </div>
  </div>
<div id="fb-root"></div>
<script>

(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/es_LA/all.js#xfbml=1&appId=458747400865661";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk')); 
  
  $(function(){
    $('.carousel').carousel({
        interval: 3000,
      pause: 'hover'
    });
  });
</script>

app/views/joins/join.js.erb
var y = window.pageYOffset;
document.documentElement.style.overflowY = "hidden";

window.onscroll = function(){
	window.scroll(0, y);
};
$('#modal-id').fadeIn('fast');
$('#modal-id').html("<%= escape_javascript(render :partial => 'join', :object => @join) %>");
$('#modal-id').click(function(){
	window.onscroll = null;
	document.documentElement.style.overflowY = "scroll";
});
$(document).keyup(function(e) {
  if (e.keyCode == 27) { $('#modal-id').show();
	window.onscroll = null;
	document.documentElement.style.overflowY = "scroll";
   }   // esc
});

$('.close-button').click(function(){
	$('#modal-id').fadeOut('fast');
});

app/views/layouts/_footer.html.erb
<div class="span10">
	<div id="footer">
		<div class="span10">
			
	</div>
</div> 

<!-- Site Meter -->
<script type="text/javascript" src="http://s51.sitemeter.com/js/counter.js?site=s51chupandero">
</script>
<noscript>
<a href="http://s51.sitemeter.com/stats.asp?site=s51chupandero" target="_top">
<img src="http://s51.sitemeter.com/meter.asp?site=s51chupandero" alt="Site Meter" border="0"/></a>
</noscript>
<!-- Copyright (c)2009 Site Meter -->

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <%= link_to image_tag('http://i1321.photobucket.com/albums/u543/Julio_Ahuactzin/logo_zps39cb8c6a.png', style: "width:140px"), root_path, class: "brand", :onmousedown => "_gaq.push(['_trackEvent', 'Home', 'Index_Chupandero', 'Index']);"  %>
		
           <div class="nav-collapse collapse">
            <ul class="nav">
              <li>
                <%= link_to '<i class="icon-list-alt icon-white"></i>Regístrate'.html_safe, registro_path %>
              </li>
              <li>
                <%= link_to '<i class="icon-info-sign icon-white"></i>Contacto'.html_safe, contacto_path %>
              </li>
              <li>
                <%= link_to '<i class="icon-glass icon-white"></i>Todas las reseñas'.html_safe, root_path %>
              </li>
            </ul>
           <!-- <ul class="nav pull-right">
              <li>
                <%= link_to "Únete", join_path, {:id => "modal", :rel => "tab", :remote => true, 'data-controls-modal' =>  "modal-window", 'data-backdrop' => true, 'data-keyboard' => true} %>
              </li>
              </ul>			 -->
          </div>
        </div>
      </div>
    </div>

app/views/layouts/_header2.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
		      <%= link_to image_tag('http://i1321.photobucket.com/albums/u543/Julio_Ahuactzin/logo_zps39cb8c6a.png', style: "width:120px"), root_path, class: "brand" %>
        <!--  <div class="nav-collapse collapse">
            <ul class="nav">
              <li>
					<a><i class="icon-glass icon-white"></i>Bares destacados</a>
              </li>
              <li>
                	<a><i class="icon-info-sign icon-white"></i>Contacto</a>
              </li>
            </ul> -->
			 <ul class="nav pull-right">
				<% if user_signed_in? %>
                 <li class="divider-vertical"></li>
                 <li class="dropdown">
                   <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sesion de <strong><%= current_user.email %></strong> <b class="caret"></b></a>
                   <ul class="dropdown-menu">
                     <li><%= link_to "Editar", edit_user_registration_path %></li>
                     <li><%= button_to "Cerrar sesion", destroy_user_session_path, :method => :delete %></li>
                   </ul>
                 </li>
				<% else %>
				<li><%= link_to "Registrarse", new_user_registration_path %></li>
				<li class="divider-vertical"></li>
                <li><%= link_to "Iniciar sesión", new_user_session_path %></li>
				<% end %>
			  </ul>
          </div>
        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chupandero</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= metamagic :title => "Chupandero", :description => "Encuentra los mejores bares de Puebla", :keywords => %w(keyword1 keyword2 keyword3) %>
</head>
<body style="background-color:black">
	<% flash.each do |name, msg| %>
	  <% if msg.class == Array %>
	    <% msg.each do |message| %>
	      <%= content_tag :div, message, :id => "flash_#{name}", :class => "alert" %>
	    <% end %>
	  <% else %>
      <%= content_tag :div, msg, :id => "flash_#{name}", :class => "alert" %>
  <% end %>
<% end %>
	<%= render 'layouts/header' %>
	<div style="margin-top:3%" class="row-fluid">
		<%= yield %>
		<div id="modal-id"></div>
	</div>
	<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-39749157-1', 'chupandero.com');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/layouts/registro.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chupandero</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% flash.each do |name, msg| %>
	  <% if msg.class == Array %>
	    <% msg.each do |message| %>
	      <%= content_tag :div, message, :id => "flash_#{name}", :class => "alert" %>
	    <% end %>
	  <% else %>
      <%= content_tag :div, msg, :id => "flash_#{name}", :class => "alert" %>
  <% end %>
<% end %>
	<%= render 'layouts/header2' %>
	<div style="margin-top:3%" class="container">
		<div class="row">
			<%= yield %>
		</div>
	</div>
	<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-39749157-1', 'chupandero.com');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/layouts/show_bar.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chupandero</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= metamagic :title => "Chupandero", :description => "Encuentra los mejores bares de Puebla", :keywords => %w(keyword1 keyword2 keyword3) %>
</head>
<body>
	<% flash.each do |name, msg| %>
	  <% if msg.class == Array %>
	    <% msg.each do |message| %>
	      <%= content_tag :div, message, :id => "flash_#{name}", :class => "alert" %>
	    <% end %>
	  <% else %>
      <%= content_tag :div, msg, :id => "flash_#{name}", :class => "alert" %>
  <% end %>
<% end %>
	<%= render 'layouts/header' %>
	<div style="margin-top:3%" class="row-fluid">
		<div class="row">
			<div id="modal-id"></div>
			<%= yield %>
		</div>
	</div>
	<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-39749157-1', 'chupandero.com');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/static_pages/_join.html.erb
<div class="modal-chupandero">
  <div style="float:right">
  	<button type="button" class="close-button" data-dismiss="modal" aria-hidden="true">X</button>
  </div>
  <div class="modal_body">
       <%= form_for Join.new do |f| %>
          <div class="field">
              <%= f.label :Email %>
              <%= f.text_field :email %>
           </div>
           <div class="actions">
             <%= f.submit %>
           </div>
        <% end %>
  </div>
</div>

app/views/static_pages/chupanderos.html.erb
<h1>StaticPages#chupanderos</h1>
<p>Find me in app/views/static_pages/chupanderos.html.erb</p>

app/views/static_pages/contacto.html.erb
<div style="background-color:white" class="container">
	<div class="row">
		<div class="span12">
			<div class="span6 offset1">
				<h1>El Chupandero esta hecho con amor en Puebla.</h1>
				<p>Te interesa nuestro trabajo, ¡contactanos! <br/>
					con gusto recibimos tus sugerencias y comentarios.</p>
				<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com.mx/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=Z%C3%B3calo,+Juan+de+Palafox+y+Mendoza,+Centro+Hist%C3%B3rico,+Puebla&amp;aq=1&amp;oq=zocalo+pue&amp;sll=19.004986,-98.212795&amp;sspn=0.006107,0.009645&amp;ie=UTF8&amp;hq=Z%C3%B3calo,+Juan+de+Palafox+y+Mendoza,+Centro+Hist%C3%B3rico,+Puebla&amp;ll=19.043684,-98.198096&amp;spn=0.006295,0.006295&amp;t=m&amp;output=embed"></iframe><br /><small></small>
			</div>
			<div style="margin-top:10%"class="span5"><div class="fb-like" data-href="https://www.facebook.com/chupandero" data-send="true" data-width="450" data-show-faces="true"></div>
		</div>
			<div style="margin-top:5%" class="span5">
	            <form action="MAILTO:chupanderopuebla@gmail.com" method="post" enctype="text/plain">
					Name:<br />
					<input type="text" name="Nombre" value="Tu nombre" /><br />
					E-mail:<br />
					<input type="text" name="Correo" value="Tu correo" /><br />
					Comment:<br />
					<input type="text" name="Comment" value="Tu comentario" size="50" />
					<br /><br />
					<input type="submit" value="Enviar">
					<input type="reset" value="Borrar">
		
				  </form>	
			  </div>
		</div>
	</div>
	<%= render 'layouts/footer' %>
</div>

<script type="text/javascript">
(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/es_LA/all.js#xfbml=1&appId=458747400865661";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk')); 

  </script>